### ISSUE TITLE
MEGA ISSUE: Grants Round Six Release Candidate Blockers

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/gitcoin-web#70]
Creating this to pull in disparate tasks & issues I see as blockers to cutting a release candidate build. There are additional "stretch goals" and nice-to-have tasks, but these are must haves.

- [x] Final tweaks to `POST` request after checkout (https://github.com/ScopeLift/gitcoin-web/pull/40#issuecomment-642666078)
- [x] Wiring up the sustain grants button (https://github.com/ScopeLift/gitcoin-web/issues/69)
- [x] Expand activity feed on grant details (https://github.com/ScopeLift/gitcoin-web/issues/53)
- [x] Remove link to recurring donations on details page
- [x] Remove `fund.js`, `fund.html`
- [x] Fix to ensure no negative values at checkout (https://github.com/ScopeLift/gitcoin-web/issues/67)
- [x] Setup & link to "How It Works" page for grants cart (https://github.com/ScopeLift/gitcoin-web/issues/42)
- [ ] SMS Fixes From Miguel
  - [ ] https://github.com/ScopeLift/gitcoin-web/issues/65
  - [ ] https://github.com/ScopeLift/gitcoin-web/issues/59#issuecomment-642521768
- [x] Fix Safari cart bug (https://github.com/ScopeLift/gitcoin-web/issues/38)
- [x] Get CLR Esimates showing in the cart (https://github.com/ScopeLift/gitcoin-web/issues/25)
- [x] Mainnet bulk txs contract deployment (https://github.com/ScopeLift/gitcoin-web/issues/19)
- [x] Merging branch to remove need to deploy contract for a grant (https://github.com/gitcoinco/web/pull/6823)

**Comment by mds1** [comment]
Round 6 has started and all of these have been completed, so closing this issue
